id: netlify-access-token
info:
  name: Netlify Access Token
  author: prowl
  severity: high
  description: Netlify personal access token (base64url value in a netlify context) for the Netlify API.
  reference:
    - https://docs.netlify.com/api/get-started/#authentication
  tags: netlify,saas,credentials,token
category: saas
matchers-condition: and
matchers:
  - type: word
    words:
      - netlify
      - nfp_
    condition: or
  - type: regex
    regex:
      - '\bnfp_[A-Za-z0-9_]{36}\b'
      - '(?i)netlify[a-z0-9_\- "'':=]{0,20}\b([A-Za-z0-9_-]{40,46})\b'
  - type: entropy
    min: 3.5
extractors:
  - type: regex
    regex:
      - '\bnfp_[A-Za-z0-9_]{36}\b'
      - '(?i)netlify[a-z0-9_\- "'':=]{0,20}\b([A-Za-z0-9_-]{40,46})\b'
    group: 1
